// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var brick;
    brick = "<div class='brick small'></div>";
    $(document).on("click", ".gridly .brick", function(event) {
      var $this, size;
      var sizeflag;
      event.preventDefault();
      event.stopPropagation();
      $this = $(this);
      $this.toggleClass('small');
      $this.toggleClass('large');
      if ($this.hasClass('small')) {
        size = 140;
      }
      if ($this.hasClass('large')) {
        size = 300;
      }
      $this.data('width', size);
      $this.data('height', size);
      
      var clickid = this.getAttribute('id');
      
      if($this.hasClass('large')){
    	  document.getElementById("content_s"+clickid).style.display='none';
    	  document.getElementById("content_l"+clickid).style.display='table-cell'; 
      }
      if($this.hasClass('small')){
    	  document.getElementById("content_l"+clickid).style.display='none';
    	  document.getElementById("content_s"+clickid).style.display='table-cell';
      }
      
      return $('.gridly').gridly('layout');
    });
    
    $(document).on("click", ".gridly .delete", function(event) {
      var $this;
      event.preventDefault();
      event.stopPropagation();
      $this = $(this);
      $this.closest('.brick').remove();
      return $('.gridly').gridly('layout');
    });
    
    $(document).on("click", ".cancel", function(event){
    	event.preventDefault();
    	event.stopPropagation();
    	document.getElementById("createProjectPop").style.display="none";
    })
    
    $(document).on("click", ".add", function(event) {
      event.preventDefault();
      event.stopPropagation();
      $('.gridly').append(brick);
	  document.getElementById("createProjectPop").style.display="none";
      return $('.gridly').gridly();
    });
    
    return $('.gridly').gridly();
  });

}).call(this);
